language: minimal
dist: xenial

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: y

script:
- sudo /snap/bin/lxd.migrate -yes
- sudo /snap/bin/lxd waitready
- sudo /snap/bin/lxd init --auto
- sudo snapcraft --use-lxd

addons:
  snaps:
    - name: snapcraft
      channel: edge
      confinement: classic
    - name: lxd
      channel: edge

deploy:
  provider: snap
  snap: cjp256-ant-hello-world*.snap
  channel: edge
  skip_cleanup: true
